#使用代理去获取代理IP
proxy:
  host: 127.0.0.1
  port: 10809

#配置信息
config:
  #监听IP
  ip: 0.0.0.0
  #webApi监听端口
  port: 8080
  #http隧道代理端口
  httpTunnelPort: 8111
  #socket隧道代理端口
  socketTunnelPort: 8112
  #隧道代理更换时间秒
  tunnelTime: 60
  #可用IP数量小于‘proxyNum’时就去抓取
  proxyNum: 30
  #代理IP验证间隔秒
  verifyTime: 1800
  #抓取/检测状态线程数
  threadNum: 200

#ip源
spider:
  - name: "proxyscrape"
    method: "GET"
    urls:
      - "https://api.proxyscrape.com/v4/free-proxy-list/get?request=display_proxies&proxy_format=protocolipport&format=text"
      - "https://github.com/proxifly/free-proxy-list/raw/refs/heads/main/proxies/protocols/http/data.txt"
    ip: '(\d+?\.\d+?.\d+?\.\d+?):\d+'
    port: '\d+?\.\d+?.\d+?\.\d+?:(\d+)'

  - name: "proxy代理"
    method: "GET"
    urls:
      - "https://www.us-proxy.org/"
      - "https://www.socks-proxy.net/"
    ip: '(\d+?\.\d+?.\d+?\.\d+?):\d+'
    port: '\d+?\.\d+?.\d+?\.\d+?:(\d+)'
  #   proxy: true
#通过插件，扩展ip源
#spiderPlugin:
#  #插件名
#  - name: test
#    #运行命令，返回的结果要符合格式
#    run: 'text.exe'

#通过文件导入ip
#spiderFile:
#  #插件名
#  - name: test1
#    #运行命令，返回的结果要符合格式
#    path: 'ip.txt'
#
#

