#使用代理去获取代理IP
proxy:
  host: 127.0.0.1
  port: 10809

#配置信息
config:
  #监听IP
  ip: 0.0.0.0
  #webApi监听端口
  port: 8080
  #http隧道代理端口
  httpTunnelPort: 8111
  #socket隧道代理端口
  socketTunnelPort: 8112
  #隧道代理更换时间秒
  tunnelTime: 60
  #可用IP数量小于‘proxyNum’时就去抓取
  proxyNum: 100
  #抓取间隔秒
  # proxyTime: 1800
  #代理IP验证间隔秒
  verifyTime: 1800
  verifyWeb: "http://httpbin.org/get"
  #验证超时时间秒
  verifyTimeout: 1
  #抓取/检测状态线程数
  threadNum: 500

#ip源
spider:
  - name: "proxyscrape"
    method: "GET"
    urls:
      - https://api.proxyscrape.com/v4/free-proxy-list/get?request=display_proxies&proxy_format=protocolipport&format=text
      - https://cdn.jsdelivr.net/gh/proxifly/free-proxy-list@main/proxies/protocols/http/data.txt
      - https://cdn.jsdelivr.net/gh/BreakingTechFr/Proxy_Free/proxies/http.txt
      - https://cdn.jsdelivr.net/gh/officialputuid/KangProxy/http/http.txt
      - https://cdn.jsdelivr.net/gh/dpangestuw/Free-Proxy/http_proxies.txt
      - https://cdn.jsdelivr.net/gh/r00tee/Proxy-List/Https.txt
      - https://cdn.jsdelivr.net/gh/trio666/proxy-checker/http.txt
      - https://cdn.jsdelivr.net/gh/MuRongPIG/Proxy-Master/http.txt
      - https://cdn.jsdelivr.net/gh/Zaeem20/FREE_PROXIES_LIST/blob/master/http.txt
      - https://cdn.jsdelivr.net/gh/vmheaven/VMHeaven-Free-Proxy-Updated/http.txt
      - https://cdn.jsdelivr.net/gh/databay-labs/free-proxy-list/blob/master/http.txt
    ip: '(\d+?\.\d+?.\d+?\.\d+?):\d+'
    port: '\d+?\.\d+?.\d+?\.\d+?:(\d+)'

  # - name: "proxy代理"
  #   method: "GET"
  #   urls:
  #     - "https://www.us-proxy.org/"
  #     - "https://www.socks-proxy.net/"
  #   ip: '(\d+?\.\d+?.\d+?\.\d+?):\d+'
  #   port: '\d+?\.\d+?.\d+?\.\d+?:(\d+)'
  #   proxy: true
#通过插件，扩展ip源
#spiderPlugin:
#  #插件名
#  - name: test
#    #运行命令，返回的结果要符合格式
#    run: 'text.exe'

#通过文件导入ip
#spiderFile:
#  #插件名
#  - name: test1
#    #运行命令，返回的结果要符合格式
#    path: 'ip.txt'
#
#

